return {
    arduino = "arduino",
    c = "c",
    cpp = "cpp",
    css = "css",
    dapui = {
        "dap-repl",
        "dapui_breakpoints",
        "dapui_console",
        "dapui_scopes",
        "dapui_stacks",
        "dapui_watches",
    },
    dashboard = "dashboard",
    go = "go",
    gomod = "gomod",
    gotmpl = "gotmpl",
    gowork = "gowork",
    html = "html",
    htmx = "htmx",
    javascript = "javascript",
    json = "json",
    jsx = "javascriptreact",
    liquid = "liquid",
    lua = "lua",
    markdown = "markdown",
    nix = "nix",
    noice = "noice",
    notify = "notify",
    nvimtree = "NvimTree",
    outline = "Outline",
    templ = "templ",
    tsx = "typescriptreact",
    typescript = "typescript",
    webc = "webc",
}
