return {
    require("plugins.editor.tree-sitter"),
    require("plugins.editor.nvim-cmp"),
    require("plugins.editor.indent-blankline"),
    require("plugins.editor.nvim-autopairs"),
    require("plugins.editor.nvim-colorizer"),
    require("plugins.editor.nvim-comment"),
    require("plugins.editor.nvim-surround"),
    require("plugins.editor.nvim-emmet"),
    require("plugins.editor.nvim-ts-autotag"),
    require("plugins.editor.nvim-ufo"),
    require("plugins.editor.todo-comments"),
    require("plugins.editor.nvim-lightbulb"),
    require("plugins.editor.webc"),
}
